apiVersion: v1
kind: Service
metadata:
  name: processor-service # Kubernetes service metadata name
  labels:
    app: processor-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8081
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    app: processor-service
