---
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://host.docker.internal:53179
  name: k3d-gateway-cluster
contexts:
- context:
    cluster: k3d-gateway-cluster
    user: admin@k3d-gateway-cluster
  name: k3d-gateway-cluster
current-context: k3d-gateway-cluster
kind: Config
users:
- name: admin@k3d-gateway-cluster
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrakNDQVRlZ0F3SUJBZ0lJZG54N3dIT1JySHN3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOemcxT1RBMk5ESTFNQjRYRFRJMk1EZ3dOVEEwTURjd05Wb1hEVEkzTURndwpOVEEwTURjd05Wb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJGekRRem8rK0taRDF1ZUEKL2pzeC9zMXRwbVNoRk1hYmYwVnFXaEh2NjJkTjFwQ2dVYjBrb0NMTU1CcXhIdVNmQldGa2FwclpScmNYS256aApteHdlaG1xalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCVGIxMnlHL1dram1RNXVTODVyMWhMZE9vZElOVEFLQmdncWhrak9QUVFEQWdOSkFEQkcKQWlFQTU1dVRObm96K0czZGh1R0g2Mno4dGhVZkdkWlJWOWFlS2JyaXhhTFBvdkVDSVFDQ3lSRGExUVhiK0tBUApGaFJyQzhqNzBJN0pOc2g1dE5nV25NOXk2NmJ6blE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCZURDQ0FSMmdBd0lCQWdJQkFEQUtCZ2dxaGtqT1BRUURBakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwClpXNTBMV05oUURFM09EVTVNRFkwTWpVd0hoY05Nall3T0RBMU1EUXdOekExV2hjTk16WXdPREF5TURRd056QTEKV2pBak1TRXdId1lEVlFRRERCaHJNM010WTJ4cFpXNTBMV05oUURFM09EVTVNRFkwTWpVd1dUQVRCZ2NxaGtqTwpQUUlCQmdncWhrak9QUU1CQndOQ0FBU2Z4N01mZTIrVjArSU56dDRqckRCKzIvTHM1eDBJWUpzcWd0cFIzc3RHCjZBRlV1YmNtMStydSs5VEdQMnhTQTA1QXlZUTlGenhXWEpiNlhqU2VQUUZFbzBJd1FEQU9CZ05WSFE4QkFmOEUKQkFNQ0FxUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVUyOWRzaHYxcEk1a09ia3ZPYTlZUwozVHFIU0RVd0NnWUlLb1pJemowRUF3SURTUUF3UmdJaEFKa2Z0VTljNWZRVmxwNzlRNXJENXhjV1c0eHlPT3RaCnJ5SXl5TS9KSGFLeUFpRUFyeXhQbkppekc3eTRhNmcwSDc4SE50UmVGQ1dCUU5xWGJBKzQ1YnE1eGlZPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSU05MEh1V25DSm5MZWMxeC9pU1VzTTJTL242cGlCaDE0ck03dTZBcDE4bm5vQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFWE1ORE9qNzRwa1BXNTREK096SCt6VzJtWktFVXhwdC9SV3BhRWUvclowM1drS0JSdlNTZwpJc3d3R3JFZTVKOEZZV1JxbXRsR3R4Y3FmT0diSEI2R2FnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
