apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consumer-api-gateway # Name displayed in ArgoCD web UI
  namespace: argocd # Must be applied in argocd namespace
spec:
  project: default
  source:
    repoURL: 'https://github.com/akc276/customer-api-gateway.git' # Path to your Git repo
    targetRevision: main
    path: helm/consumer-api-gateway # Relative path to Helm chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc' # Target local Kubernetes cluster API
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true